const actionType = {
    //User

    //Post
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_LIMIT: 'GET_POSTS_LIMIT',
    //Company
    GET_COMPANIES: 'GET_COMPANIES',
    GET_COMPANY_BY_ID: 'GET_COMPANY_BY_ID',
    GET_COMPANIES_LIMIT: 'GET_COMPANIES_LIMIT',
    //User

    //Candidate

    //Other Data
    GET_CAREER: 'GET_CAREER',
    GET_ACADEMIC_LEVEL: 'GET_ACADEMIC_LEVEL',
    GET_DISTRICT: 'GET_DISTRICT',
    GET_POSITION: 'GET_POSITION',
    GET_WORKING_TYPE: 'GET_WORKING_TYPE',
};

export default actionType;
