const actionType = {
    //User

    //Post
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_LIMIT: 'GET_POSTS_LIMIT',
    GET_POST_BY_ID: 'GET_POST_BY_ID',
    GET_POST_EDIT: 'GET_POST_EDIT',
    SET_POST_NULL: 'SET_POST_NULL',
    SET_POSTS_NULL: 'SET_POSTS_NULL',
    SET_POST_EDIT_NULL: 'SET_POST_EDIT_NULL',
    //Company
    GET_COMPANIES: 'GET_COMPANIES',
    GET_COMPANY_BY_ID: 'GET_COMPANY_BY_ID',
    GET_COMPANIES_LIMIT: 'GET_COMPANIES_LIMIT',
    SET_COMPANY_NULL: 'SET_COMPANY_NULL',
    SET_COMPANIES_NULL: 'SET_COMPANIES_NULL',
    GET_COMPANY_EDIT: 'GET_COMPANY_EDIT',
    SET_COMPANY_EDIT_NULL: 'SET_COMPANY_EDIT_NULL',
    //User

    //Candidate
    GET_CANDIDATES: 'GET_CANDIDATES',
    GET_CANDIDATES_LIMIT: 'GET_CANDIDATES_LIMIT',
    GET_CANDIDATE_BY_ID: 'GET_CANDIDATE_BY_ID',
    SET_CANDIDATE_NULL: 'SET_CANDIDATE_NULL',
    SET_CANDIDATES_NULL: 'SET_CANDIDATES_NULL',
    GET_CANDIDATE_EDIT: 'GET_CANDIDATE_EDIT',
    SET_CANDIDATE_EDIT_NULL: 'SET_CANDIDATE_EDIT_NULL',
    SET_ALL_CANDIDATES_NULL: 'SET_ALL_CANDIDATES_NULL',
    //Other Data
    GET_CAREER: 'GET_CAREER',
    GET_ACADEMIC_LEVEL: 'GET_ACADEMIC_LEVEL',
    GET_DISTRICT: 'GET_DISTRICT',
    GET_POSITION: 'GET_POSITION',
    GET_WORKING_TYPE: 'GET_WORKING_TYPE',

    //Auth
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    //User
    GET_CURRENT: 'GET_CURRENT',

    //Report
    GET_REPORT: 'GET_REPORT',
};

export default actionType;
